sudo: required
services:
  - docker

before_install:
  - docker build -t player66/docker-react -f Dockerfile.dev .

scripts:
  - docker run player66/docker-react npm run test -- --coverage --detectOpenHandles --forceExit